export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	OPEN_MODAL: 'OPEN_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',
	LOGOUT: 'LOGOUT',
	SET_NOT_FOUND_PRODUCTS: 'SET_NOT_FOUND_PRODUCTS',
	SET_SEARCH: 'SET_SEARCH',
	SET_IS_LOADED_PRODUCTS: 'SET_IS_LOADED_PRODUCTS',
	SET_PRODUCT_DATA: 'SET_PRODUCT_DATA',
	RESET_PRODUCT_DATA: 'RESET_PRODUCT_DATA',
	ADD_ITEM_BASKET: 'ADD_ITEM_BASKET',
	REMOVE_ITEM_BASKET: 'REMOVE_ITEM_BASKET',
	UPDATE_QUANTITY: 'UPDATE_QUANTITY',
};
