export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	OPEN_MODAL: 'OPEN_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',
	LOGOUT: 'LOGOUT',
	SET_PRODUCTS_DATA: 'SET_PRODUCTS_DATA',
	SET_NOT_FOUND_PRODUCTS: 'SET_NOT_FOUND_PRODUCTS',
	RESET_PRODUCTS: 'RESET_PRODUCTS',
	SET_SEARCH: 'SET_SEARCH',
};
